/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.FileUtils;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FileUtilTest {
    @Test void ExistsTrue() {
        assertTrue(FileUtils.isValidDirectory("src/test/resources/test/test2"), "someLibraryMethod should return 'true'");
    }
    @Test void ExistsFalse() {
        assertFalse(FileUtils.isValidDirectory("src/test/resources/pol"), "someLibraryMethod should return 'false'");
    }
    @Test void DirectoryTrue() {
        assertTrue(FileUtils.isValidDirectory("src/test/resources/test/test2"), "someLibraryMethod should return 'true'");
    }
    @Test void DirectoryFalse() {
        assertFalse(FileUtils.isValidDirectory("src/test/resources/test/pol.txt"), "someLibraryMethod should return 'false'");
    }
    @Test void EmptyFalse() {
        assertFalse(FileUtils.isValidDirectory("src/test/resources"), "someLibraryMethod should return 'false'");
    }
    @Test void EmptyTrue() {
        assertTrue(FileUtils.isValidDirectory("src/test/resources/test/test2"), "someLibraryMethod should return 'true'");
    }

}