/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cat.uvic.teknos.m06.FileUtils;

public class FileUtils {
    public boolean someLibraryMethod() {
        return true;
    }
}
